### PR TITLE
Simplify installing

### PR DESCRIPTION
**Pull request by revolter**
Remove the need of saving the install script locally

### CODE REVIEW

**Comment by Shougo** [comment]
Reject.
Because, you should the script locally.

**Comment by revolter** [comment]
What check? I thought it's ok since [brew does it too][1] and a couple more that I don't remember.

  [1]: http://brew.sh

**Comment by revolter** [comment]
@Shougo, ping?

**Comment by Shougo** [comment]
https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

**Comment by revolter** [comment]
That makes no sense. It says about creating a complex script, running in a python server that does this, while the NeoBundle's script is a static file hosted on GitHub which is open source. So the user can check it directly in the browser before running any command.

**Comment by Shougo** [comment]
I think the user should check the script if possible.
If you don't want to check the script, you can use `curl | bash`.
But I don't want to change the documentation.

**Comment by revolter** [comment]
Ok, but you got my point that you can't hijack it through GitHub, right? Also, I'm pretty sure that less than 1% of people actually check if the downloaded script is the same as the one in the repository.

**Pull request closed without merging**
