### PR TITLE
Improve autoload behavior

### PR DESCRIPTION
**Pull request by Shougo**
* autoload keys are deprecated
* `:NeoBundle` set lazy flag automatically

### CODE REVIEW

**Comment by Shougo** [comment]
Testing users are well come.

**Comment by NigoroJr** [comment]
Is TOML not supported yet for this branch? Using the old keys (like `filetypes`) works but `on_ft` doesn't seem to work.

**Comment by Shougo** [comment]
@NigoroJr It is already supported.  Please upload minimal .vimrc and reproduce ways.

**Comment by NigoroJr** [comment]
@Shougo I can create a new issue if that's better.

## Files
### `.vimrc`
```vim
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim', 'autoload'

call neobundle#load_toml(expand('~/sample.toml'), {'lazy': 1})

call neobundle#end()
filetype plugin indent on
syntax on
```

### `~/sample.toml`
```toml
[[plugins]]
repository = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'cpp'
# With this it works
# filetypes = 'cpp'
```

## Steps to reproduce
1. Start vim with: `vim -u ~/vimrc foo.cpp`
2. Type in `cout`

### Expected outcome
The keyword `cout` gets highlighted (default vim syntax highlighting doesn't highlight `cout` but this plugin does). Works as expected if `filetype = 'cpp'` is used instead in the TOML file.

**Comment by Shougo** [comment]
@NigoroJr I cannot reproduce it.
My ESP skills result:

You must use `/.vim/bundle/neobundle.vim_autoload` instead of `/.vim/bundle/neobundle.vim/`.
Because, neobundle is installed in it by `NeoBundleFetch 'Shougo/neobundle.vim', 'autoload'`.

**Comment by NigoroJr** [comment]
@Shougo Ahh, you're absolutely right. That fixed it, thanks. I also converted all my current configurations to the new format, and everything seems to be working fine (checked `on_ft`, `on_cmd`, `on_map`, `on_unite`, and `on_i`)

**Comment by Shougo** [comment]
@NigoroJr Thanks!

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
